import openai
import numpy as np
from numpy.linalg import norm
from DocUploads.utils import preprocess_text


def get_embedding(text, model):
    """
    Generate embeddings using openai API.

    Parameters:
    ----------
    text: The string to be converted into embeddings
    model: The embedding model to use

    Returns:
    ------------
    The Openai Embeddings created as an array of floats
    """
    text = text.replace("\n", " ")
    text = preprocess_text(text)
    return openai.Embedding.create(input=[text], model=model)['data'][0]['embedding']


class TextSimilarity():
    def __init__(self, embedding_model) -> None:
        """
        Class that generates similarity scores and decides marks for a particular user.
        """
        self.embedding_model = embedding_model

    def compare(self, gpt_generated_ans: str, user_ans: str):
        """
        Find cosine similarity of both model answer and user answer.

        Parameters:
        -----------
        gpt_generate_ans: The answer generated by the model as the ground truth
        user_ans: The answer generated by scanning the user answer sheet with the OCR model

        Returns:
        --------
        cosine similarity between both strings as a floating point number
        """
        gpt_generated_ans_embedding = get_embedding(
            gpt_generated_ans, self.embedding_model)
        user_ans_embedding = get_embedding(user_ans, self.embedding_model)

        return np.dot(gpt_generated_ans_embedding, user_ans_embedding)/(norm(gpt_generated_ans_embedding)*norm(user_ans_embedding))

    def determine_marks(self, max_marks: int, gpt_generated_ans: str, user_ans: str):
        """
        Give the marks scored by the student.
        Parameters:
        -----------
        gpt_generate_ans: The answer generated by the model as the ground truth
        user_ans: The answer generated by scanning the user answer sheet with the OCR model
        max_marks: The maximum amount of marks that can be scored by the user

        Returns:
        --------
        marks scored by the student as an integer.
        """
        similarity = self.compare(gpt_generated_ans, user_ans)
        print(similarity)
        return round(max(0, similarity*max_marks)) if similarity > 0.74 else 0
